### PR TITLE
Create a proper Readme - hell f* yeah

### PR DESCRIPTION
**Pull request by dmesq**

### CODE REVIEW

**Comment by dmesq** [comment]
Teach Daniel Reigada how to create a proper Readme.
Level of importance: high
Level of glue: banana

**Review by DReigada — CHANGES_REQUESTED** [review]
Thank you for your contribution.

Could you please split the changes into more than one commit?
It's complicated to review this amount of changes without a logical division into commits.

**Comment by dmesq** [comment]
You're welcome. Always glad to help inferior persons

No I cannot, because that would render the whole point of using high energy physics to study dark matter ineffective

**Comment by DReigada** [comment]
I'm not sure if I follow your response.
The fact that the study of dark matter, using high energy physics, is rendered obsolete, would only mean that a new and more effective method was discovered. That would not only improve our understanding of how such a complex area can be applied to the development of mutant guinea pigs, but also allow us to overcome our incapability, as simple human beings, of creating useful pull requests on GitHub.

**Comment by DReigada** [comment]
I hope my comment was not too complex, for such a simple mind as yours, to understand.
Thank you for your attempt

**Pull request closed without merging**
